services:
  os-dev:
    image: os-dev-debug
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "5900:5900"
    volumes:
      - ..:/workspace:cached
