graphics: yes
timeout: 0
verbose: yes

/Kernel x86_32
    protocol: multiboot1
    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/boot/root_process.elf
    module_path: boot():/boot/child_process.elf
    resolution: 640x400x32
